service: awstemp

plugins:
  - serverless-esbuild

configValidationMode: error

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true

package:
  individually: true

params:
  default:
    logRetentionInDays: 1
  prod:
    logRetentionInDays: 7
  test:
    logRetentionInDays: 7

provider:
  architecture: arm64
  deploymentMethod: direct
  logRetentionInDays: ${param:logRetentionInDays}
  name: aws
  region: eu-central-1
  runtime: nodejs20.x
  stackName: ${self:service}-${sls:stage}
  versionFunctions: false

  iam:
    role:
      statements:
        - Effect: 'Deny'
          Action:
            - lambda:InvokeFunction
          Resource: '*'

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps
    STAGE: ${sls:stage}

functions:
  replaceMe:
    handler: 'src/handler.replaceMe'
